version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "swift"
    directory: "/"
    allow:
      - dependency-type: all
    schedule:
      interval: "weekly"
      time: "02:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
    groups:
      dependencies:
        patterns:
          - "*"
