# Copyright 2020-2021 Dave Verwer, Sven A. Schmidt, and other contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.7'

# logging & monitoring visualiser

services:

  grafana:
    image: grafana/grafana:9.1.6
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_SERVER_ROOT_URL: "${GF_SERVER_ROOT_URL}"
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - app_backend
    deploy:
      placement:
        constraints:
          # placement for data persistence
          - node.labels.grafana_node == true


  # logging

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/loki.yml
    configs:
      - source: loki_cfg
        target: /loki.yml
    networks:
      - app_backend


  promtail:
    image: grafana/promtail:2.6.1
    command: -config.file=/promtail.yml
    configs:
      - source: promtail_cfg
        target: /promtail.yml
    volumes:
      - /var/lib/docker/containers:/var/log
    networks:
      - app_backend
    deploy:
      mode: global


  # monitoring

  prometheus:
    image: prom/prometheus:v2.37.1
    volumes:
      - prometheus_data:/prometheus
    command: --config.file=/prometheus.yml
    configs:
      - source: prometheus_cfg
        target: /prometheus.yml
    networks:
      - app_backend
    deploy:
      placement:
        constraints:
          # placement for data persistence
          - node.labels.prometheus_node == true


  pushgateway:
    image: prom/pushgateway:v1.4.3
    networks:
      - app_backend


  node-exporter:
    image: prom/node-exporter:v1.3.1
    networks:
      - app_backend
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command: --path.procfs /host/proc --path.sysfs /host/sys --collector.textfile.directory /etc/node-exporter/ --collector.filesystem.mount-points-exclude "^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: global


  cadvisor:
    image: google/cadvisor:v0.45.0
    networks:
      - app_backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    deploy:
      mode: global


configs:
  loki_cfg:
    file: ./infrastructure/loki.yml
  promtail_cfg:
    file: ./infrastructure/promtail.yml
  prometheus_cfg:
    file: ./infrastructure/prometheus.yml


volumes:
  grafana_data:
  prometheus_data:


networks:
  app_backend:
    external: true
