// Copyright Dave Verwer, Sven A. Schmidt, and other contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Fluent

struct UpdateCustomCollectionAddKey: AsyncMigration {
    func prepare(on database: Database) async throws {
        // We need to clear the custom_collections table, because the existing rows don't have
        // `key` values and their existence prevents the update.
        // They will be automatically regenerated by the next reconciliation run.
        try await CustomCollection.query(on: database).delete()
        try await database.schema("custom_collections")
            .field("key", .string, .required)
            .unique(on: "key")
            .update()
    }

    func revert(on database: Database) async throws {
        try await database.schema("custom_collections")
            .deleteField("key")
        // The unique key constraint is automatically deleted when the field is deleted,
        // no explicit clean up is required.
            .update()
    }
}
