name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:5.2-bionic
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: swiftpackageindex_test
          POSTGRES_USER: swiftpackageindex
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Install libssl-dev
      run: apt-get update && apt-get install libssl-dev
    - name: Run Tests
      run: swift test --enable-test-discovery -v
