name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:5.2-bionic
    steps:
    - uses: actions/checkout@v2
    - name: Install libssl-dev
      run: sudo apt-get install libssl-dev
    - name: Run Tests
      run: swift test --enable-test-discovery -v
